name: GH-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          # This ensures the latest stable version of Flutter is used
          channel: 'stable'
      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          # This is the full build command you want to run.
          # We've removed --web-renderer to fix the error.
          arguments: 'build web --release --base-href=/game/'
          baseHref: /game/