name: GH-Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build web
        run: flutter build web --release --base-href /game/
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /game/
